language: julia
os:
  - linux
  - osx
  - windows
arch:
  - amd64
  - arm64
julia:
  - 1.3
  - nightly
notifications:
  email: false
after_success: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
